# Generated by Django 4.1.7 on 2023-08-13 10:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GasUtilCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_customer_tracking_id', models.CharField(blank=True, max_length=50)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('csr_employee_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_util_csr_employee', to=settings.AUTH_USER_MODEL)),
                ('customer_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_util_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gas_util_customer',
            },
        ),
        migrations.CreateModel(
            name='GasUtilServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_service', models.CharField(max_length=100)),
                ('service_request_details', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('resolved_on', models.DateTimeField(default=datetime.datetime(2023, 8, 13, 10, 39, 32, 301172, tzinfo=datetime.timezone.utc))),
                ('service_paid_on', models.DateTimeField(default=datetime.datetime(2023, 8, 13, 10, 39, 32, 301172, tzinfo=datetime.timezone.utc))),
                ('customer_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csr.gasutilcustomers')),
            ],
            options={
                'db_table': 'gas_util_service_request',
            },
        ),
        migrations.CreateModel(
            name='GasUtilServiceRequestAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='attachments')),
                ('gas_util_service_request_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csr.gasutilservicerequest')),
            ],
            options={
                'db_table': 'gas_util_service_request_attachments',
            },
        ),
    ]
